### ISSUE TITLE
在 Chrome 浏览器点开翻译以后，download 按钮闪动

### ISSUE THREAD

**Issue by artxia** [oe/download-git-userscript#1]
script version 0.2.6
Chrome 89.0.4389.82
macOS 11.2.2

**Comment by artxia** [comment]
另外在 commits 页面也有下载按钮，应该去掉

**Comment by oe** [comment]
已修正, 可更新到 0.2.7 尝试
https://openuserjs.org/scripts/oe/Download_github_repo_online
https://greasyfork.org/en/scripts/411834-download-github-repo-sub-folder
