### ISSUE TITLE
Github changed the layout

### ISSUE THREAD

**Issue by biast12** [oe/download-git-userscript#11]
looks like they changed something as the button is not showing anymore

**Comment by oe** [comment]
The "download" button which has been a built-in feature could be found here .
![CleanShot 2023-12-16 at 14 49 57](https://github.com/oe/download-git-userscript/assets/1655294/967b3791-563b-4046-badb-4ed4854b6109)

But you still can  download partial contents of a repo by clicking the file icons in repo file list
![CleanShot 2023-12-16 at 14 52 45](https://github.com/oe/download-git-userscript/assets/1655294/451ef108-78d7-4a57-9d26-27b4385c88ad)

**Comment by biast12** [comment]
The userscript does still not work, they may have made a build in feature to download now but the button this userscript makes is gone and not working

**Comment by oe** [comment]
Are you using the latest version of this script? 
You may disable this script to recheck.

If the problem continues, please provide more details, like script version, screenshots of this issue.

**Comment by biast12** [comment]
yes i'm using the latest version of the script
![image](https://github.com/oe/download-git-userscript/assets/53872542/34f8cb38-cae1-47ae-b8bf-e218e8a2ec8b)

and the button does not appear
![image](https://github.com/oe/download-git-userscript/assets/53872542/35f1db3f-7f3e-4e7e-851d-24ed6a01f356)

**Comment by oe** [comment]
here it is. 

![](https://private-user-images.githubusercontent.com/1655294/290977635-967b3791-563b-4046-badb-4ed4854b6109.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MjgwMDUsIm5iZiI6MTcwMjcyNzcwNSwicGF0aCI6Ii8xNjU1Mjk0LzI5MDk3NzYzNS05NjdiMzc5MS01NjNiLTQwNDYtYmFkYi00ZWQ0ODU0YjYxMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTZUMTE1NTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTJkOGJlYjM2YzM2NDgzZmJiYWFiMGM5NmRiMmVmYWVkZWFlMzU0ZDNhMGE0MTViNWNhZDM3MGQ0ZjQzMDFiNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TEtvME3adtQ_gAioWooMu5ZJhN8w8g0AT5OC4kGSCCw)

**Comment by biast12** [comment]
you got this download button?
![image](https://github.com/oe/download-git-userscript/assets/53872542/85968964-cdd3-46ec-9c77-6eefd2a4897c)

**Comment by oe** [comment]
issue has been fixed with this commit 11f395a

you may update to  v0.7.0 and have a try

* [install script via greasyfork](https://greasyfork.org/scripts/411834-download-github-repo-sub-folder/code/Download%20github%20repo%20sub-folder.user.js), [greasyfork home page](https://greasyfork.org/scripts/411834-download-github-repo-sub-folder)
* [install script via openuserjs](https://openuserjs.org/install/oe/Download_github_repo_online.user.js), [openuserjs home page](https://openuserjs.org/scripts/oe/Download_github_repo_online)

**Comment by biast12** [comment]
actual goat, thanks!
