### ISSUE TITLE
从某个文件单独进入的 commits 页面依旧有按钮

### ISSUE THREAD

**Issue by artxia** [oe/download-git-userscript#2]
例如这个页面，上面有一个很长的按钮：
https://github.com/oe/download-git-userscript/commits/master/webpack.config.js
应该去掉。

**Comment by oe** [comment]
已修正, 可更新到 0.3.0 尝试
https://openuserjs.org/scripts/oe/Download_github_repo_online
https://greasyfork.org/en/scripts/411834-download-github-repo-sub-folder

**Comment by artxia** [comment]
貌似在线升级有点问题？ 点升级会出现重新安装0.2.7

**Comment by oe** [comment]
你用的哪个平台装的脚本? 可以刷新看下

**Comment by artxia** [comment]
greasyfork 
刚才可能是缓存问题，删了重下了两次就有了
感谢～
