### ISSUE TITLE
[讨论]功能增减建议

### ISSUE THREAD

**Issue by Ethkuil** [oe/download-git-userscript#5]
## 减

![image](https://user-images.githubusercontent.com/77615248/176353984-f8e114f5-e2ca-472a-bd92-87688fd32851.png)

文件界面，GitHub已提供复制内容按钮，则"Copy"按键与功能可考虑移除。

## 增

* 显示仓库总大小。安置位置（供参考）：右侧license的上方或下方
* 点击图标下载相应文件/文件夹。这样需下载多个部分文件时就无需逐个点开。
![image](https://user-images.githubusercontent.com/77615248/176356092-3f988174-4ca0-4b0d-aea4-eeb6cb9e8431.png)

我尚未接触JavaScript，故无法提PR，只能提出参考建议如上。

**Comment by oe** [comment]
谢谢你的建议👍

copy 按钮我会抽空去掉; 关于仓库大小的建议, 可以找到相关的用户脚本或者浏览器扩展, 本脚本核心功能是提供仓库部分下载功能, 其他已有的轮子就不再重造.

**Comment by Ethkuil** [comment]
> 谢谢你的建议👍
> 
> copy 按钮我会抽空去掉；关于仓库大小的建议，可以找到相关的用户脚本或者浏览器扩展，本脚本核心功能是提供仓库部分下载功能，其他已有的轮子就不再重造.

好的，那请问「点击图标下载相应文件 / 文件夹」的功能有考虑支持吗？

**Comment by oe** [comment]
可以考虑的

**Comment by oe** [comment]
已经支持了, 可以通过仓库 readme 中的安装方式来升级安装

注意: 两个用户脚本托管网站都有cdn缓存, 可能得刷新多次才能安装到最新版本 `0.4.0`
