### ISSUE TITLE
功能建议：单文件下载不打包

### ISSUE THREAD

**Issue by Ethkuil** [oe/download-git-userscript#7]
单文件下载也打包，其实挺反人类的，特别是下载多个文件时，需要逐个解压，几乎完全是多余操作。

当然这是因为DownGit默认打包下载文件。DownGit已经至少2年未更新了，有人提了 [PR](https://github.com/MinhasKamal/DownGit/pull/50) 提供了不打包的选项，也许可以考虑用一下。

**Comment by oe** [comment]
已经处理了, 升级到 `0.5.0` 即可

**Comment by Ethkuil** [comment]
有点困惑，现在点击图标变成在浏览器中打开了，这样的话和直接点击 文件夹名/文件名 没什么区别。而本来的功能是「下载」。没能理解用意。

其实我的意思只是「下载单个文件时，直接下载，而不打包成zip」。

此外，测试发现点击「Download」按钮也是在浏览器中打开，而非下载。可能修改出了点问题。

**Comment by oe** [comment]
区别很大: 实现成本很低, 没有github api频率限制
浏览器自身支持的文件会在浏览器中直接打开, 如果你需要保存到磁盘, 按 cmd + s 即可
如果是浏览器不支持的文件会自动下载.

Download 按钮的问题已经修复, 更新至 `0.5.1` 即可

**Comment by Ethkuil** [comment]
原来如此，我之前没想到API的问题。

但在当前版本，下载单文件的步骤从「点击」变为「点击→等待新标签加载完毕→按快捷键保存→**删去多余的.txt扩展名**」，步骤繁琐且费时。
如果有办法直接下载文件的话就更好了。

附上我的环境：Windows 10, Chrome 102.0.5005

**Comment by oe** [comment]
如果你想下载的是没后缀的文件, 即使做到直接下载, 要么会被浏览器安全警告, 要么也会被系统重命名的

不太理解你为何会有这么高频的下载单文件的需求, 这个脚本我平时也很少使用.
如果你是想要使用文件的内容, 那大可在浏览器的页面中直接复制取用, 无需再下载到本地
